### ISSUE TITLE
有没有考虑提供API接口呢？

### ISSUE THREAD

**Issue by vvvsinger** [nashaofu/wol#8]
感谢分享，项目很好用，web添加、管理设备很方便
能不能考虑加入API接口控制呢，那样就可以集成到其他自动化流程中去啦，例如IOS的快捷指令，居家的物联网自动化。

**Comment by nashaofu** [comment]
有时间可以加一下

**Comment by nashaofu** [comment]
唤醒机器可以使用这个API，应该可以满足你的需求

```bash
curl 'http://192.168.31.10:3000/api/device/wake' \
  -H 'Content-Type: application/json' \
  --data-raw '{"name":"windows","mac":"AA:BB:CC:DD:EE:FF","ip":"192.168.31.27","port":9,"uid":"IxQH8GttQYG-W3WXXIChs"}'
```

**Comment by vvvsinger** [comment]
好的，感谢！

**Comment by missqso** [comment]
> 唤醒机器可以使用这个API，应该可以满足你的需求
> 
> ```shell
> curl 'http://192.168.31.10:3000/api/device/wake' \
>   -H 'Content-Type: application/json' \
>   --data-raw '{"name":"windows","mac":"AA:BB:CC:DD:EE:FF","ip":"192.168.31.27","port":9,"uid":"IxQH8GttQYG-W3WXXIChs"}'
> ```

你好，请问uid这里可以不填吗，还是必填的

**Comment by nashaofu** [comment]
可以不填，只需要mac、port即可
